#!/bin/bash

#Starts TeamViewer daemon if it's not running and TeamViewer. If deamon is running it starts or stops TeamViewer

OTHERSERVICE="TeamViewer"
OTHERID=`pgrep -x $OTHERSERVICE`
SERVICE="teamviewerd"
if pgrep -x "$SERVICE" >/dev/null
then
    echo "$SERVICE is running"
    if pgrep -x "$OTHERSERVICE" >/dev/null
    then
        kill "$OTHERID"
    else
        teamviewer
    fi
else
    echo "$SERVICE stopped"
    # start if not running
    systemctl start teamviewerd.service
    sleep 2 
    teamviewer
    
fi
